# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0004_auto_20170729_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Book')),
            ],
        ),
        migrations.CreateModel(
            name='ReadBookRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('readBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ReadBook')),
            ],
        ),
    ]
