# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbookrecord',
            name='end_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='library.Book'),
        ),
    ]
