# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20170729_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='ratio',
            field=models.IntegerField(default=0),
        ),
    ]
