# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_readbook_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='status',
            field=models.CharField(choices=[('2', '已读'), ('1', '在读'), ('0', '待读')], default=2, max_length=1),
        ),
    ]
