# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0013_auto_20170805_0851'),
        ('tracker', '0005_auto_20170729_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField(blank=True)),
                ('thought', models.TextField(blank=True)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Book')),
            ],
        ),
    ]
